default:
	./run.sh pqxdh-model SecrecyInit SecrecyResp Authentication

test:
	./run.sh pqxdh-model SecrecyInit 

reach:
	./run.sh pqxdh-model Reach

anonymity:
	./run.sh pqxdh-model-anonymity UnbreakableKEM

anonymity-broken-kem:
	./run.sh pqxdh-model-anonymity

anonymity-compromise-ik:
	./run.sh pqxdh-model-anonymity UnbreakableKEM CompromiseIK

anonymity-broken-kem-compromise-ik:
	./run.sh pqxdh-model-anonymity CompromiseIK

anonymity-broken-dh:
	./run.sh pqxdh-model-anonymity UnbreakableKEM BrokenDH

clean:
	rm *.gen.pv -f 


